# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{a_okay}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Hart"]
  s.date = %q{2009-11-15}
  s.description = %q{A simple controller that just returns if everything is 'a okay'!}
  s.email = %q{richard@ur-ban.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "a_okay.gemspec",
     "app/controllers/a_okay_controller.rb",
     "config/routes.rb",
     "lib/a_okay.rb",
     "test/controllers/a_okay_controller_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/hates/a_okay}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple controller that just returns if everything is 'a okay'!}
  s.test_files = [
    "test/controllers/a_okay_controller_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
